version: 0.0
os: linux

files:
  - source: /
    destination: /usr/share/nginx/html/

hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/delete_default.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
