version: 0.0
os: linux

files:
  - source: index.html
    destination: /home/ubuntu/deploy-temp/

hooks:
  BeforeInstall:
    - location: scripts/delete-default.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/move-files.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
